# Global settings applied to the whole site.  
# 
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!

[build]
   command  = "npm run build"
   publish  = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"