export const white: string;
export const black: string;
export const offWhite: string;
export const darkGray: string;
export const gray: string;
export const lightSalmon: string;
export const lightGreen: string;
export const lightBlue: string;
export const transparent: string;